name: campuslink
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 41.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #state management
  get: ^4.6.6
  flutter_bloc: ^8.1.6
  provider: ^6.1.2

  #font
  google_fonts: ^6.2.1

  #storage
  sembast: ^3.7.2
  get_storage: ^2.1.1
  
  #icon
  iconsax: ^0.0.8

  #responsive
  flutter_screenutil: ^5.9.3
  
  #time
  intl: ^0.19.0
  time_picker_spinner_pop_up: ^2.0.0
  timeago: ^3.7.0
  custom_date_range_picker: ^1.1.0

  #net
  dio: ^5.5.0+1
  connectivity_plus: ^6.0.5
  
  #decoration
  flutter_spinkit: ^5.2.1
  awesome_top_snackbar: ^0.0.3

  #cached
  cached_network_image: ^3.4.0
  
  #other
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0

  #path
  path_provider: ^2.1.4

  #notification
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  rxdart: ^0.28.0

  #firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10

  #socket
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^3.0.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^4.0.0
flutter:
  
  generate: true
  uses-material-design: true

