class AppList {
  static List<String> passwordMessages = [
    "Need a password reset? That’s cute, but no.",
    "Forget your password? Guess you’ll have to start a new life.",
    "Password missing? Well, that’s just tough luck, isn’t it?",
    "Oops, no password? No entry! Enjoy your stay outside.",
    "Lost your password? Oh well, looks like the end of the road for you!",
    "Forgot your password? That’s a real bummer, but we don’t care.",
    "Password vanished? Sorry, but we’re fresh out of sympathy today.",
    "Password reset? Ha! As if we’d actually help with that.",
    "Forget your password? Consider it a sign to take a break.",
    "Password recovery? Nah, we’ll pass on that.",
    "Lost password? Sounds like a ‘you’ problem!",
    "Password gone? Maybe you should’ve written it down, huh?",
    "Forgot your password? Well, that’s what you get for not being a robot.",
    "Password reset? How about no? Try something else!",
    "Sorry, we don’t help with lost passwords. Good luck!",
    "Oops! Password recovery? Not our department.",
    "Forget your password? Tough luck, we don’t do resets!",
    "Password missing? Sorry, we’re on a break.",
    "Password recovery? Nah, you’re on your own!",
    "Oops, no can do! Password recovery is not in our skill set.",
    "Lost your password? Sorry, we’re fresh out of solutions.",
    "Password gone? We’d help, but we’re on strike today!",
    "Forget your password? That’s too bad, we don’t do miracles.",
    "Password retrieval? Sorry, that’s above our pay grade.",
    "Password reset? We’re afraid that’s a no-go!",
    "Forget your password? Looks like you’re stuck!",
    "Password gone missing? Sorry, we don’t do lost and found.",
    "Oops! Password recovery service is currently… unavailable. Forever.",
    "Lost password? Well, that’s unfortunate. Good luck with that!",
    "Forgot your password? That’s a shame. Guess you’ll never get back in!",
    "Password reset? Nope, not happening. Better luck next time!",
    "Lost your password? Well, that’s unfortunate. Maybe try remembering next time?",
    "Password recovery? We’d love to help, but we don’t feel like it.",
    "Oops! Forgot your password? Looks like you’re locked out forever!",
    "Password gone? Sorry, that’s your problem, not ours!",
  ];
  static const listOfError = [
    "Oops! Your fingers slipped, didn't they? Check your email or password.",
    "Did you forget your login details? Give it another try!",
    "Nope, that's not it. Email or password needs a second look.",
    "Almost there! One of these isn't quite right—email or password?",
    "Uh-oh! Something's off. Double-check that email or password.",
    "Not this time! Give your email and password another go.",
    "Oops! The email or password monster strikes again!",
    "Nice try! But your email or password seems to have a typo.",
    "So close! But not quite. Email or password needs some love.",
    "Whoops! That email or password combo needs a little tweaking.",
    "Hmm... Are you sure that’s your email or password?",
    "Yikes! That email or password didn’t make the cut.",
    "Did you change your email or password while I wasn’t looking?",
    "Oh no! Something went wrong with your email or password.",
    "Looks like your email or password took a detour. Try again!",
    "Bzzz! Incorrect email or password. Give it another shot.",
    "Uh-oh! Your email or password seems to be on vacation.",
    "No luck this time! Your email or password might need a redo.",
    "Denied! That email or password needs a little more attention.",
    "Are you playing a guessing game? Double-check that email or password!",
    "Uh-oh! Hope your eyes aren't playing tricks—check that email or password!",
    "Lost your glasses? That email or password doesn’t seem right!",
    "Nope, not it! Maybe your keyboard is just messing with you?",
    "Almost! But are your eyes closed while typing? Check that email or password!",
    "Houston, we have a vision problem! Double-check your email or password.",
    "Not today! Did you forget your reading glasses for that email or password?",
    "Oops! Did you try typing with your eyes shut?",
    "Nice try! But it seems your email or password went on a mystery tour.",
    "So close! But you might need a magnifying glass for that email or password.",
    "Whoops! That email or password combo seems to be on vacation. Try again!",
    "Hmm... Did you type that email or password in the dark? Give it another shot!",
    "Yikes! That email or password didn’t pass the vision test.",
    "Did you change your email or password in your dreams? Because it’s not working!",
    "Oh no! Something’s blurry. Your email or password might need a second look.",
    "Looks like your email or password took a wrong turn. Maybe they’re lost?",
    "Bzzz! That email or password is out of focus. Want to try again?",
    "Uh-oh! Are your eyes closed? Because that email or password isn't right.",
    "Nope! Your email or password seems to be playing hide and seek.",
    "Denied! That email or password didn’t even try to pass the test!",
    "Are you sure you’re seeing this right? Double-check that email or password!",
  ];

  static List<String> mockUserWhoNotedInstalled(user) => [
        '$user wasn’t on the Campus Link train. Retro vibes?',
        'Looks like $user missed the Campus Link memo.',
        '$user isn’t setting records with Campus Link downloads.',
        '$user isn’t joining the Campus Link era anytime soon.',
        '$user must think Campus Link is too mainstream.',
        'Seems $user isn’t into tech-savvy awards with Campus Link.',
        '$user is probably waiting for Campus Link 2.0.',
        '$user missed the memo on modern conveniences. Campus Link, anyone?',
        '$user isn’t breaking new ground with Campus Link.',
        '$user isn’t thrilled about Campus Link. Retro charm?',
        '$user isn’t jumping on the Campus Link party wagon.',
        '$user isn’t upgrading to Campus Link. Nostalgia, maybe?',
        '$user isn’t on the app bandwagon. Too avant-garde?',
        'Looks like $user isn’t ready for Campus Link. Vintage soul?',
        '$user isn’t setting tech trends with Campus Link.',
        '$user isn’t thrilled about Campus Link. Too futuristic?',
        '$user isn’t rushing to install Campus Link. Tech-free holiday?',
        'Looks like $user isn’t catching up with modern tech.',
        '$user isn’t making tech history with Campus Link.',
        '$user isn’t graced by Campus Link’s magic. Old-fashioned, maybe?'
      ];

  static List<String> follow = [
    "I’m following you. Accept the follow, or prepare for my epic dad jokes!",
    "Just followed you, don’t make it weird!",
    "Started following you, don’t ghost me, please!",
    "I’m following you, accept or I’ll send cat memes!",
    "I’m now officially following you, be cool about it!",
    "Following you, don’t leave me hanging in the digital void!",
    "Just followed, accept or prepare for my terrible jokes!",
    "Following you, don’t leave me hanging with your posts!",
    "I’m now following you, time to get this friendship rolling!",
    "Just followed you, don’t make me start a campaign for acceptance!",
    "I’m following you, time to make this digital thing real!",
    "Following you now, accept or face my relentless memes!"
  ];

  static List<String> unfollow = [
    "Just hit unfollow—don’t worry, I’m still cheering you on from a distance!",
    "Unfollowed you—don’t be sad, I’m still your biggest fan in my head!",
    "I’m unfollowing—don’t worry, I’m still here in spirit (and the occasional like)!",
    "Just unfollowed you—don’t take it personally, I’m just trying to save my sanity!",
    "Unfollowed you—don’t fret, I’m still watching your stories in secret!",
    "I’m now unfollowing—don’t worry, I’m still rooting for you from the sidelines!",
    "Unfollowed you—don’t take it the wrong way, I’m still your number one lurker!",
    "Just unfollowed—don’t be bummed, I’m still sending good vibes your way!",
    "I’m unfollowing—don’t worry, I’ll still remember your posts fondly!",
    "Unfollowed you—don’t worry, I’m still your unofficial fan club president!"
  ];

  static List<String> viewed = [
    "Just viewed your profile—don’t worry, I’m not a stalker, just a fan!",
    "Checked out your profile—don’t worry, I’m still keeping it casual!",
    "I’ve seen your profile—don’t fret, I’m just here for the memes!",
    "Viewed your profile—don’t take it personally, I was just curious!",
    "Just looked at your profile—no worries, I’m just a casual observer!",
    "I peeked at your profile—don’t be alarmed, I’m just a friendly lurker!",
    "Checked out your profile—don’t worry, I’m not making any judgments!",
    "Viewed your profile—don’t be weirded out, I was just admiring your posts!",
    "Just scrolled through your profile—no big deal, just checking out the content!",
    "I took a peek at your profile—don’t worry, I’m still just a fan from afar!"
  ];
}
