final List<String> keywords = [
  'hie',
  'hey',
  'hello',
  'Hey',
  'Hie',
  'Hello',
  'who are you',
  'what is flutter',
  'fuck',
  'bitch',
  'otha',
  'omala',
  'sorry',
  'i love you',
  'i love u',
  'do u support lgbtq',
  'lgbtq',
  'gay',
  'Gay',
  'lesbian',
  'Lesbian',
  'like kcg',
  'like KCG',
  'hate kcg',
  'hate KCG',
  'who is sri krishna',
  'who is sk',
  'who is krithick',
  'who is ravi trichy',
  'created you',
  'created u',
  'help'
];

final List<String> responses = [
  'Hey,Wassup',
  'Hey,Wassup',
  'Hey,Wassup',
  'Hey,Wassup',
  'Hey,Wassup',
  'Hey,Wassup',
  'I am a bot created by Sri Krishna, a proud KCGPT',
  'Flutter transforms the app development process. Build, test, and deploy beautiful mobile, web, desktop, and embedded apps from a single codebase.',
  'Otha Unaku Avlodhan Mariyadha!',
  'Otha Unaku Avlodhan Mariyadha!',
  'Otha Unaku Avlodhan Mariyadha!',
  'Otha Unaku Avlodhan Mariyadha!',
  'Good! i have forgiven you. dont do that again!',
  'Love You Too',
  'Love You Too',
  'What the fuck is lgbtq?',
  'What the fuck is lgbtq?',
  'Am Straight,and i don\'t give a fuck about it',
  'Am Straight,and i don\'t give a fuck about it',
  'Am Straight,and i don\'t give a fuck about it',
  'Am Straight,and i don\'t give a fuck about it',
  'I love Kcg and proud to be a KCGian bot',
  'I love Kcg and proud to be a KCGian bot',
  'Absolutely not i love KCG',
  'Absolutely not i love KCG',
  'Developer Of Campus~Link',
  'Developer Of Campus~Link',
  'Developer Of Campus~Link',
  'Dharmalingam GrandSon!',
  'Sri Krishna',
  'Sri Krishna',
  '''Should you require assistance, I am pleased to provide the contact information of a developer. Please find the details below:
Developer: Sri Krishna
Contact Number: +91 9345927994
Please feel free to reach out to Sri Krishna for any further inquiries or support.''',
];
